---

- name: rockylinux8
  box: generic/rocky8
  memory: 4096
  interfaces: [{'network_name': 'private_network', 'ip': '192.168.56.100'}]
- name: debian11
  box: generic/debian11
  memory: 4096
  interfaces: [{'network_name': 'private_network', 'ip': '192.168.56.101'}]
- name: ubuntu2004
  box: generic/ubuntu2004
  memory: 4096
  interfaces: [{'network_name': 'private_network', 'ip': '192.168.56.102'}]
