---

- name: Install required OS packages
  ansible.builtin.package:
    name: "{{ awx_os_packages }}"
    state: present
  become: yes

- name: Install required pypi packages
  ansible.builtin.pip:
    name: "{{ awx_pip_packages }}"
  become: yes
