---

- name: Install ansible/git/make
  ansible.builtin.package:
    name:
      - ansible
      - git
      - make
    state: present
  become: yes

- name: Install pexect
  ansible.builtin.pip:
    name: pexpect
  become: yes
