---

- name: Converge pre playbook
  ansible.builtin.import_playbook: converge-pre.yml

- name: Converge
  hosts: all
  become: "yes"
  vars:
    awx_version: HEAD
  tasks:
    - name: Include role 'ansible-role-awx_docker'
      ansible.builtin.include_role:
        name: ansible-role-awx_docker
