---

name: CI

on:
  pull_request:
  push:
    branches-ignore:
      - master
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1"

defaults:
  run:
    working-directory: "de-it-krachten/ansible-role-awx_docker"


jobs:

  lint:
    name: "${{ matrix.name }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "ansible4"
            ansible: ">4,<5"
            ansible_lint: ">5,<6"
          - name: "ansible5"
            ansible: ">5,<6"
            ansible_lint: ">6,<7"
          - name: "ansible6"
            ansible: ">6,<7"
            ansible_lint: ">6,<7"

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'


      - name: Show runner info
        run: |
          hostname -f

      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/

      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

      - name: Install test dependencies.
        run: pip3 install "ansible${{ matrix.ansible }}" "ansible-lint${{ matrix.ansible_lint }}" yamllint jmespath e2j2 yq

      - name: Show component versions
        run: |
          ansible --version
          ansible-lint --version
          yamllint --version

      - name: Lint code.
        run: |
          set -e
          yamllint .
          ansible-lint --exclude molecule/

